# Generated by Django 5.0.4 on 2024-04-18 12:30

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='profiles'),
        ),
    ]
